#!/usr/bin/env ruby

require 'optparse'
require 'webrick'

ng = false
blink = true
greeting = "Hello World!"
server = false
port = 8000

OptionParser.new do |opts|
  opts.banner = "Usage: hello [OPTION]\nPrint a friendly, customizable greeting."

  opts.separator ""

  opts.on("-h", "--help", "display this help and exit") do
    puts opts
    exit
  end

  opts.on("-v", "--version", "display version information and exit") do
    puts "super-hello 0.1.0-rc1"
    exit
  end

  opts.separator ""

  opts.on("-n", "--next-generation", "use next-generation greeting format") do
    ng = true
  end

  opts.on("-g", "--greeting=TEXT", "use TEXT as the greeting message") do |custom_greeting|
    greeting = custom_greeting
  end

  opts.on("-s", "--server", "launch http server to deliver greetings") do |server_port|
    server = true
  end

  opts.on("-p", "--port=PORT", "http server port") do |server_port|
    port = server_port.to_i
  end

end.parse!

greeting_body =
  if ng
    horizontal_line = "+#{"-" * (greeting.length+2)}+"

    [horizontal_line,
     "| #{greeting} |",
     horizontal_line].join("\n")
  else
    greeting
  end

if server
  server = WEBrick::HTTPServer.new :Port => port
  server.mount_proc '/' do |req, res|
    res.body = greeting_body + "\n"
  end

  trap 'INT' do server.shutdown end

  server.start
else
  puts greeting_body
end
